{{- $custom_path := `{title|slugify}/_index.md` -}}
{{- if (index site.Params.admin.collections .) -}}
  {{- with (index site.Params.admin.collections .).path -}}
    {{- $custom_path = . }}
  {{- end -}}
{{- else -}}
  {{- $custom_path = . }}
{{- end -}}
{{- $custom_path = replace $custom_path "{{" "{" }}
{{- $custom_path = replace $custom_path "}}" "}" }}
{{- $custom_path = replace $custom_path "{slug}" "{title|slugify}.md" }}
{{- $custom_path = replace $custom_path "{year}" "{date|year}" }}
{{- $custom_path = replace $custom_path "{month}" "{date|month}" }}
{{- $custom_path = replace $custom_path "{day}" "{date|day}" }}

create: {
  path: "[relative_base_path]/{{$custom_path}}"
},