{{- $fields := partial "admin/func/GetCloudcannonInputsAndStructures.html" . }}

# Config
paths:
  static: static
  uploads: {{ site.Params.admin.media.public_folder | default "static/images/uploads" }}

# Snippets
_snippets_imports:
  hugo: true

# Collections
{{ transform.Remarshal "yaml" (partial "admin/cms/cloudcannon/collection/index.html" .) }}

# Structures
{{ transform.Remarshal "yaml" (partial "admin/cms/cloudcannon/structures.js" $fields.structures) }}
