{{- $fields := partial "admin/func/GetCloudcannonInputsAndStructures.html" . }}

{{/* Config */}}
paths:
  static: static
  uploads: {{ site.Params.admin.media.public_folder | default "static/images/uploads" }}

{{/* Snippets */}}
_snippets_imports:
  hugo: true

{{/* Collections */}}
{{ transform.Remarshal "yaml" (partial "admin/cms/cloudcannon/collection/index.html" .) }}

{{/* Collections Group */}}
{{ transform.Remarshal "yaml" (partial "admin/cms/cloudcannon/collection/group.html" .) }}

{{/* Inputs */}}
{{ transform.Remarshal "yaml" (partial "admin/cms/cloudcannon/inputs.js" $fields.inputs) }}

{{/* Structures */}}
{{ transform.Remarshal "yaml" (partial "admin/cms/cloudcannon/structures.js" (dict "context" . "structures" $fields.structures)) }}

